Dev
RaulGracia/pravega-data-importer pull request #1
Opened 2022-09-27 17:37 UTC by ns-dell

**Change log description**  
- Separates existing code for mirroring stream into committing metadata changes, actions and jobs.

**Purpose of the change**  
- Pravega data importer

**What the code does**  
- Separates existing code for mirroring stream into committing metadata changes, actions and jobs.

**How to verify it**  
- Run this command from command line in the directory:
```
./gradlew build
./gradlew run --args="\
  --action-type stream-mirroring \
  --input-stream examples/network \
  --input-startAtTail false \
  --output-stream examples/network-cloud \
  --output-controller tcp://127.0.0.1:9090 \
  --fixedRoutingKey edge1 \
 "
```

2022-11-09 15:53 UTC, ShwethaSNayak commented on README.md
> +## Kafka-Stream-Mirroring: Continuously copying a Pravega stream to another Pravega stream
This should be Continuously copying a Kafka stream to Pravega stream

2022-12-16 14:37 UTC, RaulGracia requested changes

2022-12-16 14:37 UTC, RaulGracia commented on build.gradle
> +//    implementation "io.pravega:pravega-connectors-flink-${flinkShortVersion}_${flinkScalaVersion}:${pravegaFlinkConnectorVersion}"
Please, clean up from this file all the unnecessary imports and comments like this.

2022-12-16 14:37 UTC, RaulGracia commented on gradle.properties
>  bucket4jVersion=4.4.1
Do we use all the variables defined here? If not, please delete the unused ones.

2022-12-16 14:37 UTC, RaulGracia commented on src/main/java/io/pravega/dataimporter/actions/AbstractAction.java
> +        log.info("\n\n\nJob ID: " + jobClient.getJobID().toString() + "\n\n");
Please, delete the "\n" from this log, it should be enough just printing the job id plus some test that describes what it is.

2022-12-16 14:37 UTC, RaulGracia commented on src/main/java/io/pravega/dataimporter/actions/AbstractAction.java
> +        log.info("\n\n\nJob ID: " + jobClient.getJobID().toString() + "\n\n");
Also, the signature of this method has changed, so the comments should change too. Why are you not using the regular Javadoc tags like `@param` or `@returns`?

2022-12-16 14:37 UTC, RaulGracia commented on src/main/java/io/pravega/dataimporter/jobs/AbstractJob.java
> +     * Concrete implementations use this method to submit Flink jobs to the Flink cluster.
Same in this file (and others) about javadoc.

2023-01-10 15:54 UTC, RaulGracia approved these changes

2023-02-22 08:03 UTC, merged